# Word Embedding Techniques using Embedding Layer in Keras

In [1]:
import tensorflow
import keras

2024-02-17 17:23:55.046314: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-17 17:23:55.046628: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-17 17:23:55.217432: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = ['the glass of milk', 'The glass of juice', 'the cup of tea', 'I am a good boy', 
       'I am a good developer', 'understand the meaning of the words', 'your videos are good',
        'Hi my name is sushant twayana and i am studying engineering'
       ]

In [4]:
sent

['the glass of milk',
 'The glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of the words',
 'your videos are good',
 'Hi my name is sushant twayana and i am studying engineering']

In [5]:
# Vocabulary size
voc_size = 10000

**One Hot Representation -> Provides the index size for each and every word in the sentence**

In [6]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[2711, 3359, 8327, 6474], [2711, 3359, 8327, 554], [2711, 1507, 8327, 4774], [656, 4126, 3574, 329, 3296], [656, 4126, 3574, 329, 3127], [6561, 2711, 4017, 8327, 2711, 266], [4719, 5411, 7043, 329], [4959, 58, 6586, 5334, 8041, 9367, 9382, 656, 4126, 3984, 7738]]


**Onehot Repre ----> Embedding Layer in Keras**

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

Here, each word in the embedding must be represented by the same word lenght size. In this we consider the word_length_max = 8

In [9]:
sent_length = 8 # maximum length of the word that is to be represented
embedded_docs = pad_sequences(onehot_repr,padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 2711 3359 8327 6474]
 [   0    0    0    0 2711 3359 8327  554]
 [   0    0    0    0 2711 1507 8327 4774]
 [   0    0    0  656 4126 3574  329 3296]
 [   0    0    0  656 4126 3574  329 3127]
 [   0    0 6561 2711 4017 8327 2711  266]
 [   0    0    0    0 4719 5411 7043  329]
 [5334 8041 9367 9382  656 4126 3984 7738]]


In [10]:
dim = 10 #features

model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
# word converted into vector maps
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 139ms/step
[[[ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445
   -0.01279641  0.04275452  0.01808628 -0.01474531  0.034716  ]
  [ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445
   -0.01279641  0.04275452  0.01808628 -0.01474531  0.034716  ]
  [ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445
   -0.01279641  0.04275452  0.01808628 -0.01474531  0.034716  ]
  [ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445
   -0.01279641  0.04275452  0.01808628 -0.01474531  0.034716  ]
  [-0.01286716 -0.04345382 -0.00462898 -0.01279183  0.03244925
    0.04992274  0.02557621 -0.00409795 -0.01181101  0.03003547]
  [ 0.03288127  0.02237083  0.00794385  0.04008997  0.04167126
    0.02979216  0.01407968  0.0171045   0.02999726  0.01119355]
  [-0.01593918 -0.04277433  0.04216527 -0.00968514  0.00745441
   -0.04497803  0.00652296  0.00669746  0.0343593   0.0093181 ]
  [-0.00331601 -0.04931637  0.04668775 -0.01857934 -0.0488

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2711, 3359, 8327, 6474], dtype=int32)

In [14]:
# each is converted into the 10 dimension vector wrt one sentence
print(model.predict(embedded_docs[0]))

1/1 [==============================] - 0s 53ms/step
[[ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445 -0.01279641
   0.04275452  0.01808628 -0.01474531  0.034716  ]
 [ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445 -0.01279641
   0.04275452  0.01808628 -0.01474531  0.034716  ]
 [ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445 -0.01279641
   0.04275452  0.01808628 -0.01474531  0.034716  ]
 [ 0.01259723 -0.01066232  0.03340312  0.02485417 -0.03830445 -0.01279641
   0.04275452  0.01808628 -0.01474531  0.034716  ]
 [-0.01286716 -0.04345382 -0.00462898 -0.01279183  0.03244925  0.04992274
   0.02557621 -0.00409795 -0.01181101  0.03003547]
 [ 0.03288127  0.02237083  0.00794385  0.04008997  0.04167126  0.02979216
   0.01407968  0.0171045   0.02999726  0.01119355]
 [-0.01593918 -0.04277433  0.04216527 -0.00968514  0.00745441 -0.04497803
   0.00652296  0.00669746  0.0343593   0.0093181 ]
 [-0.00331601 -0.04931637  0.04668775 -0.01857934 -0.04882041 -0.0246573
